window.HRzImageMap = {
  "ROYAL ENFIELD": "images/bikes/ROYAL_ENFIELD_logo.jpg",
  "Scram 440 new": "images/bikes/ROYAL_ENFIELD.jpg",
  "Classic 650": "images/bikes/ROYAL_ENFIELD.jpg",
  "Bear 650": "images/bikes/ROYAL_ENFIELD.jpg",
  "Guerrilla 450": "images/bikes/ROYAL_ENFIELD.jpg",
  "Himalayan 450": "images/bikes/ROYAL_ENFIELD.jpg",
  "SUPER METEOR 650": "images/bikes/ROYAL_ENFIELD.jpg",
  "Hunter 350": "images/bikes/ROYAL_ENFIELD.jpg",
  "Himalayan": "images/bikes/ROYAL_ENFIELD.jpg",
  "Classic 350 Reborn": "images/bikes/ROYAL_ENFIELD.jpg",
  "Standard 350 Reborn": "images/bikes/ROYAL_ENFIELD.jpg",
  "Meteor 350": "images/bikes/ROYAL_ENFIELD.jpg",
  "Classic": "images/bikes/ROYAL_ENFIELD.jpg",
  "Standard": "images/bikes/ROYAL_ENFIELD.jpg",
  "Electra": "images/bikes/ROYAL_ENFIELD.jpg",
  "Interceptor": "images/bikes/ROYAL_ENFIELD.jpg",
  "Thunderbird": "images/bikes/ROYAL_ENFIELD.jpg",
  "Continental GT": "images/bikes/ROYAL_ENFIELD.jpg",
  "Scram": "images/bikes/ROYAL_ENFIELD.jpg",
  "XSR 155": "images/bikes/YAMAHA_XSR_155.jpg",
  "RX 100": "images/bikes/YAMAHA_RX_100.jpg",
  "MT 15": "images/bikes/YAMAHA_MT_15.jpg",
  "R15 V2": "images/bikes/YAMAHA_R15_V2.jpg",
  "KTM": "images/bikes/KTM_logo.jpg",
  "KTM 390 Enduro R": "images/bikes/KTM_KTM_390_Enduro_R.jpg",
  "Adventure 890": "images/bikes/KTM_Adventure_890.jpg",
  "Adventure 390": "images/bikes/KTM_Adventure_390.jpg",
  "Duke 125": "images/bikes/KTM_Duke_125.jpg",
  "Thunderbird X": "images/bikes/ROYAL_ENFIELD_Thunderbird_X.jpg",
  "YAMAHA": "images/bikes/YAMAHA_logo.jpg",
  "Aerox 155": "images/bikes/YAMAHA_Aerox_155.jpg",
  "R3": "images/bikes/YAMAHA_R3.jpg",
  "R15 V1": "images/bikes/YAMAHA_R15_V1.jpg",
  "R15 V3": "images/bikes/YAMAHA_R15_V3.jpg",
  "R15 V4": "images/bikes/YAMAHA_R15_V4.jpg",
  "R1": "images/bikes/YAMAHA_R1.jpg",
  "ADVENTURE 390 2025 Model": "images/bikes/KTM_ADVENTURE_390_2025_Model.jpg",
  "Duke 200": "images/bike_t_1.webp",
  "Duke 250 BS6": "images/bikes/KTM_Duke_250_BS6.jpg",
  "Duke 250": "images/bikes/KTM_Duke_250.jpg",
  "Duke 390": "images/bikes/KTM_Duke_390.jpg",
  "RC 390": "images/bikes/KTM_RC_390.jpg",
  "BAJAJ": "images/bikes/BAJAJ_logo.jpg",
  "NS400Z": "images/bikes/BAJAJ_NS400Z.jpg",
  "Pulsar 220": "images/bikes/BAJAJ_Pulsar_220.jpg",
  "Pulsar NS 200": "images/bikes/BAJAJ_Pulsar_NS_200.jpg",
  "Pulsar RS 200": "images/bikes/BAJAJ_Pulsar_RS_200.jpg",
  "Dominar 400": "images/bikes/BAJAJ_Dominar_400.jpg",
  "Pulsar 150": "images/bikes/BAJAJ_Pulsar_150.jpg",
  "Pulsar 180": "images/bikes/BAJAJ_Pulsar_180.jpg",
  "HONDA": "images/bikes/HONDA_logo.jpg",
  "XL750 Transalp": "images/bikes/HONDA_XL750_Transalp.jpg",
  "NX500": "images/bike_t_1.webp",
  "CB 200X": "images/bikes/HONDA_CB_200X.jpg",
  "Hness CB 350": "images/bikes/HONDA_Hness_CB_350.jpg",
  "Hornet 160R": "images/bikes/HONDA_Hornet_160R.jpg",
  "CBR 250 R": "images/bikes/HONDA_CBR_250_R.jpg",
  "CB 300": "images/bikes/HONDA_CB_300.jpg",
  "CB 350 RS": "images/bikes/HONDA_CB_350_RS.jpg",
  "CB 500X": "images/bikes/HONDA_CB_500X.jpg",
  "NX400": "images/bikes/HONDA_NX400.jpg",
  "CB650R": "images/bikes/HONDA_CB650R.jpg",
  "CBR 650R": "images/bikes/HONDA_CBR_650R.jpg",
  "CBR 1000RR": "images/bikes/HONDA_CBR_1000RR.jpg",
  "SUZUKI": "images/bikes/SUZUKI_logo.jpg",
  "Gixxer": "images/bikes/SUZUKI_Gixxer.jpg",
  "Gixxer SF": "images/bikes/SUZUKI_Gixxer_SF.jpg",
  "V Strom 250": "images/bikes/SUZUKI_V_Strom_250.jpg",
  "Hayabusa": "images/bikes/SUZUKI_Hayabusa.jpg",
  "GSX-S750": "images/bikes/SUZUKI_GSX-S750.jpg",
  "V Strom 800DE": "images/bikes/SUZUKI_V_Strom_800DE.jpg",
  "V Strom DL650": "images/bikes/SUZUKI_V_Strom_DL650.jpg",
  "HERO": "images/bikes/HERO_logo.jpg",
  "Xpulse 210": "images/bikes/HERO_Xpulse_210.jpg",
  "Mavrick 440": "images/bikes/HERO_Mavrick_440.jpg",
  "Xpulse 200": "images/bikes/HERO_Xpulse_200.jpg",
  "Impulse": "images/bikes/HERO_Impulse.jpg",
  "TRIUMPH": "images/bikes/TRIUMPH_logo.jpg",
  "Tiger 900": "images/bikes/TRIUMPH_Tiger_900.jpg",
  "Tracker 400": "images/bikes/TRIUMPH_Tracker_400.jpg",
  "Scrambler 400 x": "images/bikes/TRIUMPH_Scrambler_400_x.jpg",
  "Speed 400": "images/bikes/TRIUMPH_Speed_400.jpg",
  "Tiger Sport 660": "images/bikes/TRIUMPH_Tiger_Sport_660.jpg",
  "Tiger": "images/bikes/TRIUMPH_Tiger.jpg",
  "Trident 660": "images/bikes/TRIUMPH_Trident_660.jpg",
  "TVS": "images/bikes/TVS_logo.jpg",
  "Apache RTX 300 new": "images/bikes/TVS_Apache_RTX_300_new.jpg",
  "tvs ronin": "images/bikes/TVS_tvs_ronin.jpg",
  "Apache 200": "images/bikes/TVS_Apache_200.jpg",
  "Apache RTR 160": "images/bikes/TVS_Apache_RTR_160.jpg",
  "Apache RTR 310": "images/bikes/TVS_Apache_RTR_310.jpg",
  "HARLEY DAVIDSON": "images/bikes/HARLEY_DAVIDSON_logo.jpg",
  "Harley 440X": "images/bikes/HARLEY_DAVIDSON_Harley_440X.jpg"
};
