const products=[
{id:1,name:'Apex Leather Glove',type:'Gloves',group:'protection',price:89,tag:'Best seller',rating:'4.9',image:'assets/gloves.png',description:'Race-bred leather protection with a responsive, all-weather grip.'},
{id:2,name:'Vector Mesh Jacket',type:'Jackets',group:'protection',price:249,tag:'New',rating:'4.8',image:'assets/jacket.png',description:'Ventilated armor engineered for city heat and highway miles.'},
{id:3,name:'Rally Pro Helmet',type:'Helmets',group:'protection',price:379,tag:'',rating:'4.9',image:'assets/helmet.png',description:'A light, stable shell with a wide field of view.'},
{id:4,name:'Forge Tail Bag',type:'Accessories',group:'performance',price:129,tag:'Best seller',rating:'4.7',image:'assets/boot.png',description:'Weather-ready storage that locks to the journey.'},
{id:5,name:'Pulse Intercom',type:'Accessories',group:'performance',price:169,tag:'New',rating:'4.8',image:'assets/helmet.png',description:'Clear rider-to-rider sound for every kind of road.'},
{id:6,name:'Obsidian Riding Boot',type:'Boots',group:'protection',price:219,tag:'',rating:'4.7',image:'assets/boot.png',description:'Reinforced ankle support with all-day comfort.'},
{id:7,name:'Nomad Rain Shell',type:'Jackets',group:'protection',price:119,tag:'Limited',rating:'4.8',image:'assets/jacket.png',description:'Packable waterproof protection for surprise weather.'},
{id:8,name:'Titanium Lever Set',type:'Performance',group:'performance',price:139,tag:'',rating:'4.9',image:'assets/gloves.png',description:'Precision controls, machined for a confident pull.'}];
let cart=[],activeFilter='all',visibleCount=4;const $=s=>document.querySelector(s),money=v=>`$${v.toFixed(2)}`;
function notify(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}
function list(){let a=activeFilter==='all'?[...products]:products.filter(p=>p.group===activeFilter),s=$('#sort-select').value;if(s==='low')a.sort((a,b)=>a.price-b.price);if(s==='high')a.sort((a,b)=>b.price-a.price);return a}
function renderProducts(){const a=list();$('#product-count').textContent=`${a.length} products`;$('#product-grid').innerHTML=a.slice(0,visibleCount).map(p=>`<article class="product-card reveal"><div class="product-image">${p.tag?`<span class="pill">${p.tag}</span>`:''}<button class="heart" data-save="${p.id}" aria-label="Save ${p.name}">♡</button><button class="quick-button" data-quick="${p.id}">Quick view</button><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><small>${p.type} · <span class="rating">★ ${p.rating}</span></small><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div></article>`).join('');$('#load-more').style.display=a.length>visibleCount?'inline-flex':'none'}
function renderCart(){let total=cart.reduce((n,p)=>n+p.price*p.qty,0),count=cart.reduce((n,p)=>n+p.qty,0);$('#cart-count').textContent=count;$('#drawer-count').textContent=count;$('#cart-total').textContent=money(total);$('#cart-items').innerHTML=cart.length?cart.map(p=>`<article class="cart-item"><img src="${p.image}" alt="${p.name}"><div><small>${p.type}</small><h4>${p.name}</h4><b>${money(p.price)}</b><div class="quantity"><button data-quantity="${p.id}" data-change="-1">−</button><span>${p.qty}</span><button data-quantity="${p.id}" data-change="1">+</button></div></div><button class="remove" data-remove="${p.id}" aria-label="Remove">×</button></article>`).join(''):'<p class="empty-state">Your bag is ready when you are.</p>'}
function add(id){let p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);i?i.qty++:cart.push({...p,qty:1});renderCart();notify(`${p.name} added to your bag`)}function close(){$('.drawer').classList.remove('open');$('#search-panel').classList.remove('open');$('#quick-view').classList.remove('open');$('#overlay').classList.remove('open')}function open(id){$(id).classList.add('open');$('#overlay').classList.add('open')}
renderProducts();renderCart();
$('#cart-button').onclick=()=>open('#cart-drawer');$('#search-button').onclick=()=>{open('#search-panel');setTimeout(()=>$('#search-input').focus(),100)};$('.close-drawer').onclick=close;$('.close-search').onclick=close;$('#overlay').onclick=close;
$('#product-grid').onclick=e=>{let q=e.target.dataset.quick,s=e.target.dataset.save;if(q){let p=products.find(x=>x.id===+q);$('#quick-view').innerHTML=`<button class="close-quick">×</button><img src="${p.image}" alt="${p.name}"><div><p class="eyebrow red">${p.type} · ★ ${p.rating}</p><h2>${p.name}</h2><p>${p.description}</p><strong>${money(p.price)}</strong><div class="size-row"><button class="selected">S</button><button>M</button><button>L</button><button>XL</button></div><button class="button button-red" data-add="${p.id}">Add to bag <span>→</span></button></div>`;open('#quick-view')}else if(s){e.target.classList.toggle('saved');e.target.textContent=e.target.classList.contains('saved')?'♥':'♡';notify(e.target.classList.contains('saved')?'Saved to your wishlist':'Removed from wishlist')}};
$('#quick-view').onclick=e=>{if(e.target.matches('.close-quick'))close();if(e.target.dataset.add){add(+e.target.dataset.add);close()}if(e.target.closest('.size-row button')){e.target.parentElement.querySelector('.selected').classList.remove('selected');e.target.classList.add('selected')}};
$('#cart-items').onclick=e=>{let id=+e.target.dataset.quantity;if(id){let p=cart.find(x=>x.id===id);p.qty+=+e.target.dataset.change;if(p.qty<1)cart=cart.filter(x=>x.id!==id);renderCart()}if(e.target.dataset.remove){cart=cart.filter(x=>x.id!==+e.target.dataset.remove);renderCart();notify('Item removed')}};
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');activeFilter=b.dataset.filter;visibleCount=4;renderProducts()});$('#sort-select').onchange=renderProducts;$('#load-more').onclick=()=>{visibleCount+=4;renderProducts()};
$('#search-input').oninput=e=>{let v=e.target.value.toLowerCase();$('#search-results').innerHTML=v?products.filter(p=>(p.name+p.type).toLowerCase().includes(v)).map(p=>`<button data-result="${p.id}"><img src="${p.image}" alt=""><span><b>${p.name}</b><small>${p.type} · ${money(p.price)}</small></span><i>→</i></button>`).join('')||'<p>No gear found. Try helmet or jacket.</p>':''};$('#search-results').onclick=e=>{let b=e.target.closest('[data-result]');if(b){close();add(+b.dataset.result)}};
$('#review-next').onclick=()=>$('#review-track').append($('#review-track').firstElementChild);$('#review-prev').onclick=()=>$('#review-track').prepend($('#review-track').lastElementChild);$('#fit-button').onclick=()=>notify('Fit finder is warming up — browse the catalog.');$('#account-button').onclick=()=>notify('Rider account sign-in coming next.');$('#checkout-button').onclick=()=>notify(cart.length?'Demo checkout ready — your gear is saved.':'Add gear to your bag first.');$('#newsletter-form').onsubmit=e=>{e.preventDefault();e.currentTarget.reset();$('#form-message').textContent='You’re on the list — welcome to the ride.'};
